export const BLANK = 'BLANK';

export const TOGGLE_NEWS_SELECTED = 'TOGGLE_NEWS_SELECTED'
export const ADD_NEW_MARKER = 'ADD_NEW_MARKER'
export const UPDATE_MARKER = 'UPDATE_MARKER'

export const ADD_NEW_LAYER = 'ADD_NEW_LAYER'
export const SHOW_LAYER = 'SHOW_LAYER'
export const HIDE_LAYER = 'HIDE_LAYER'

export const DESELECT_ALL = 'DESELECT_ALL'
export const SET_IS_EXPANDED = 'SET_IS_EXPANDED'
export const SET_IS_SELECTED = 'SET_IS_SELECTED'
