export const BLANK = 'BLANK';

export const TOGGLE_NEWS_SELECTED = 'TOGGLE_NEWS_SELECTED'
export const ADD_NEW_MARKER = 'ADD_NEW_MARKER'
export const UPDATE_MARKER = 'UPDATE_MARKER'

export const ADD_NEW_LAYER = 'ADD_NEW_LAYER'
export const SHOW_LAYER = 'SHOW_LAYER'
export const HIDE_LAYER = 'HIDE_LAYER'

export const DESELECT_ALL_LAYERS = 'DESELECT_ALL_LAYERS'
export const SET_IS_EXPANDED_LAYERS = 'SET_IS_EXPANDED_LAYERS'
export const SET_IS_SELECTED_LAYERS = 'SET_IS_SELECTED_LAYERS'
export const TOGGLE_VISIBILITY_LAYERS = 'TOGGLE_VISIBILITY_LAYERS'

export const DESELECT_ALL_TOOLS = 'DESELECT_ALL_TOOLS'
export const SET_IS_EXPANDED_TOOLS = 'SET_IS_EXPANDED_TOOLS'
export const SET_IS_SELECTED_TOOLS = 'SET_IS_SELECTED_TOOLS'
export const TOGGLE_VISIBILITY_TOOLS = 'TOGGLE_VISIBILITY_TOOLS'

export const UPDATE_MODE = 'UPDATE_MODE'
export const UPDATE_GEOJSON = 'UPDATE_GEOJSON'

export const UPDATE_SELECTED_FEATURE_INDEXES = 'UPDATE_SELECTED_FEATURE_INDEXES';

export const ADD_PIN = 'ADD_PIN';
export const UPDATE_PIN = 'UPDATE_PIN';
export const TOGGLE_PIN = 'TOGGLE_PIN';

export const UPDATE_MAX_HEIGHT = 'UPDATE_MAX_HEIGHT';
